# docker-compose.yml
version: "3"
services:
    dev:
        image: python:3.11
        container_name: python_lab   # ← 名前を指定
        volumes:
        - .:/app
        working_dir: /app
        command: tail -f /dev/null
